export const Recipe = {
  meals: [
    {
      idMeal: '53014',
      strMeal: 'Pizza Express Margherita',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Italian',
      strInstructions:
        '1 Preheat the oven to 230°C.\r\n\r\n2 Add the sugar and crumble the fresh yeast into warm water.\r\n\r\n3 Allow the mixture to stand for 10 – 15 minutes in a warm place (we find a windowsill on a sunny day works best) until froth develops on the surface.\r\n\r\n4 Sift the flour and salt into a large mixing bowl, make a well in the middle and pour in the yeast mixture and olive oil.\r\n\r\n5 Lightly flour your hands, and slowly mix the ingredients together until they bind.\r\n\r\n6 Generously dust your surface with flour.\r\n\r\n7 Throw down the dough and begin kneading for 10 minutes until smooth, silky and soft.\r\n\r\n8 Place in a lightly oiled, non-stick baking tray (we use a round one, but any shape will do!)\r\n\r\n9 Spread the passata on top making sure you go to the edge.\r\n\r\n10 Evenly place the mozzarella (or other cheese) on top, season with the oregano and black pepper, then drizzle with a little olive oil.\r\n\r\n11 Cook in the oven for 10 – 12 minutes until the cheese slightly colours.\r\n\r\n12 When ready, place the basil leaf on top and tuck in!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=Mt5lgUZRoUg',
      strIngredient1: 'Water',
      strIngredient2: 'Sugar',
      strIngredient3: 'Yeast',
      strIngredient4: 'Plain Flour',
      strIngredient5: 'Salt',
      strIngredient6: 'Olive Oil',
      strIngredient7: 'Passata',
      strIngredient8: 'Mozzarella',
      strIngredient9: 'Oregano',
      strIngredient10: 'Basil',
      strIngredient11: 'Black Pepper',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '150ml',
      strMeasure2: '1 tsp ',
      strMeasure3: '15g',
      strMeasure4: '225g',
      strMeasure5: '1 1/2 tsp ',
      strMeasure6: 'Drizzle',
      strMeasure7: '80g',
      strMeasure8: '70g',
      strMeasure9: 'Peeled and Sliced',
      strMeasure10: 'Leaves',
      strMeasure11: 'Pinch',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource:
        'https://www.dailymail.co.uk/femail/food/article-8240361/Pizza-Express-release-secret-recipe-Margherita-Pizza-make-home.html',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52777',
      strMeal: 'Mediterranean Pasta Salad',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Italian',
      strInstructions:
        'Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg',
      strTags: 'Pasta,Baking',
      strYoutube: 'https://www.youtube.com/watch?v=e52IL8zYmaE',
      strIngredient1: 'mozzarella balls',
      strIngredient2: 'baby plum tomatoes',
      strIngredient3: 'fresh basil',
      strIngredient4: 'farfalle',
      strIngredient5: 'extra virgin olive oil',
      strIngredient6: 'Green Olives',
      strIngredient7: 'tuna',
      strIngredient8: 'salt',
      strIngredient9: 'pepper',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '200 g',
      strMeasure2: '250 g',
      strMeasure3: '1  bunch',
      strMeasure4: '350 g',
      strMeasure5: '3  tablespoons',
      strMeasure6: '40 g',
      strMeasure7: '200 g',
      strMeasure8: 'to taste',
      strMeasure9: 'to taste',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: 'https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52854',
      strMeal: 'Pancakes',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'American',
      strInstructions:
        'Put the flour, eggs, milk, 1 tbsp oil and a pinch of salt into a bowl or large jug, then whisk to a smooth batter. Set aside for 30 mins to rest if you have time, or start cooking straight away.\r\nSet a medium frying pan or crêpe pan over a medium heat and carefully wipe it with some oiled kitchen paper. When hot, cook your pancakes for 1 min on each side until golden, keeping them warm in a low oven as you go.\r\nServe with lemon wedges and sugar, or your favourite filling. Once cold, you can layer the pancakes between baking parchment, then wrap in cling film and freeze for up to 2 months.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg',
      strTags: 'Breakfast,Desert,Sweet,Fruity',
      strYoutube: 'https://www.youtube.com/watch?v=LWuuCndtJr0',
      strIngredient1: 'Flour',
      strIngredient2: 'Eggs',
      strIngredient3: 'Milk',
      strIngredient4: 'Sunflower Oil',
      strIngredient5: 'Sugar',
      strIngredient6: 'Raspberries',
      strIngredient7: 'Blueberries',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '100g ',
      strMeasure2: '2 large',
      strMeasure3: '300ml ',
      strMeasure4: '1 tbls',
      strMeasure5: 'to serve',
      strMeasure6: 'to serve',
      strMeasure7: 'to serve',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/2907669/easy-pancakes',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
